# Generated by Django 3.1.1 on 2021-01-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daftar_sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('deskripsi', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Data_perhari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('curah_hujan', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Data_perjam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('curah_hujan', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Data_permenit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('curah_hujan', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Data_sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('curah_hujan', models.FloatField(max_length=30)),
            ],
        ),
    ]
